### PR TITLE
drop the "aspiring"

### PR DESCRIPTION
**Pull request by nekowinston**

### CODE REVIEW

**Comment by taka0o** [comment]
So wholesome.

**Comment by rubyowo** [comment]
This PR aspires to be merged

**Comment by nyxkrage** [comment]
Perhaps :cat: :clown_face: would be more inline with the behavior displayed in the catppuccin discord

**Comment by spookyintheam** [comment]
Best PR. Merge it ASAP

**Review by sgoudham — APPROVED** [review]
LGTM

**Review by backwardspy — APPROVED** [review]

**Review by rewhile — APPROVED** [review]

**Review by sgoudham — APPROVED** [review]

**Review by sgoudham — APPROVED** [review]

**Review by sgoudham — APPROVED** [review]

**Review by backwardspy — APPROVED** [review]

**Review by backwardspy — APPROVED** [review]
i apologise for sleeping on this, thanks for the request. PR approved! :)

**Review by rewhile — APPROVED** [review]
This PR is aspiring to be merged!

**Review by sgoudham — APPROVED** [review]

**Comment by nullishamy** [comment]
Please rebase. @nekowinston

**Comment by sgoudham** [comment]
🫡

**Comment by nullishamy** [comment]
No aspirations for me 😔

**Pull request closed without merging**
